server:
  port: 8070
spring:
  application:
    name: allhystrix
eureka:
  client:
  service-url:
    defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: allhystrix-8070
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'