server:
  port: 8030
spring:
  application:
    name: allclient
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/
  #    关闭thymeleaf缓存
  thymeleaf:
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: allclient-8030
    prefer-ip-address: true